#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-sync
Version  : 1.1.2
Release  : 18
URL      : https://pecl.php.net/get/sync-1.1.2.tgz
Source0  : https://pecl.php.net/get/sync-1.1.2.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: php-sync-lib = %{version}-%{release}
BuildRequires : buildreq-php

%description
CubicleSoft PHP Extension:  Synchronization Objects (sync)
==========================================================

%package lib
Summary: lib components for the php-sync package.
Group: Libraries

%description lib
lib components for the php-sync package.


%prep
%setup -q -n sync-1.1.2
cd %{_builddir}/sync-1.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure --disable-static
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20210902/sync.so
